spring:
  neo4j:
    host: ${SPRING_NEO4J_HOST:localhost}
    port: ${SPRING_NEO4J_PORT:7474}
    username: ${SPRING_NEO4J_USERNAME:neo4j}
    password: ${SPRING_NEO4J_PASSWORD:123456}
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
